# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 240, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 110, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 240, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txt_Plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Plaintext.setGeometry(QtCore.QRect(180, 110, 361, 87))
        self.txt_Plaintext.setObjectName("txt_Plaintext")
        self.txt_Ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Ciphertext.setGeometry(QtCore.QRect(180, 240, 361, 87))
        self.txt_Ciphertext.setObjectName("txt_Ciphertext")
        self.txt_Info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Info.setGeometry(QtCore.QRect(660, 110, 361, 87))
        self.txt_Info.setObjectName("txt_Info")
        self.txt_Signa = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Signa.setGeometry(QtCore.QRect(660, 240, 361, 87))
        self.txt_Signa.setObjectName("txt_Signa")
        self.btn_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Generate.setGeometry(QtCore.QRect(600, 40, 111, 31))
        self.btn_Generate.setObjectName("btn_Generate")
        self.btn_En = QtWidgets.QPushButton(self.centralwidget)
        self.btn_En.setGeometry(QtCore.QRect(200, 360, 93, 31))
        self.btn_En.setObjectName("btn_En")
        self.btn_De = QtWidgets.QPushButton(self.centralwidget)
        self.btn_De.setGeometry(QtCore.QRect(410, 360, 93, 28))
        self.btn_De.setObjectName("btn_De")
        self.btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sign.setGeometry(QtCore.QRect(680, 360, 93, 28))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Verify.setGeometry(QtCore.QRect(890, 360, 93, 28))
        self.btn_Verify.setObjectName("btn_Verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text:"))
        self.label_4.setText(_translate("MainWindow", "Information:"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.btn_Generate.setText(_translate("MainWindow", "Generate Keys"))
        self.btn_En.setText(_translate("MainWindow", "Encrypt"))
        self.btn_De.setText(_translate("MainWindow", "Decrypt"))
        self.btn_Sign.setText(_translate("MainWindow", "Sign"))
        self.btn_Verify.setText(_translate("MainWindow", "Verify"))
